/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/ratika.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Ratika(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../../models/ratika.glb");

  const { ref, mixer } = useAnimations(animations, group);

  // Function to start the animation
  const playAnimation = () => {
    const animationClip = animations.find((clip) => clip.name === "Action.003");
    if (animationClip) {
      const action = mixer.clipAction(animationClip);

      // Set the animation speed (0.5 will reduce the speed by half)
      action.timeScale = 0.5;

      action.play();
    }
  };

  // Click event handler for the mesh
  const handleMeshClick = () => {
    playAnimation(); // Play the animation when the mesh is clicked
  };
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="AuxScene">
        <group name="Scene">
          <mesh
                      name="rail"
                      geometry={nodes.rail.geometry}
                      material={materials["Material.004"]}
                      position={[3-200, 0, -250]}
                      rotation={[Math.PI / 2, 0, 1.769]}
                      scale={1}
            onClick={handleMeshClick}

          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("../../models/ratika.glb");
